### ISSUE TITLE
Automatic closing quote mark added even when escaped

### ISSUE THREAD

**Issue by johnnywz00** [toerob/vscode-tads3tools#19]
The automatic closing delimiters are nice, so I don't want to turn them off. However, it would be good if the editor would not add a closing quote (single or double) if that quote comes right after a backslash. If I type
specialDesc = "He isn\'t blah blah"
I will end up with two single quotes before the 't', which I have to backspace. It's easy for these to not get noticed when you're typing a lot, and can cause an extra recompile.

**Comment by toerob** [comment]
Good suggestion!

**Comment by johnnywz00** [comment]
Note: it may not always add the unwanted closing quote, if there's a non-space character directly in front of the cursor... but in a lot of cases it does...

**Comment by toerob** [comment]
I have a little trouble reproducing this. I tried that particular example tou gave but it worked just fine for me. I wonder if is due to some individual setting? Anyway, would appreciate another example on how to reproduce.

**Comment by johnnywz00** [comment]
There may be other situations than this, but this is the primary one I notice: if the cursor is within a string, and the next character is a space, an unwanted quote mark will show up even when escaped. As often as I edit within an existing string, this ends up happening all the time...

**Comment by johnnywz00** [comment]
The issue also happens if the cursor is directly behind a period, a comma, a closing bracket, a closing brace, or a closing parenthesis... that's not necessarily an exhaustive list...

**Comment by toerob** [comment]
If you like you can try to build the "fixes" branch if it works better. I believe this behaviour is corrected now.

**Comment by johnnywz00** [comment]
Sorry, I'm a GitHub newbie! What do I click on to do what you're talking about?

**Comment by toerob** [comment]
If you like to build the extension from a particular branch you can clone the repo to your machine (get the git command by pressing the green code button at the first page on this github repo), then run "npm install" followed by "vsce package --no-yarn" inside the root of the repo, this will build a vsix-image that you install manually to vscode (if doing this, be sure to uninstall the previous extension first).

I'm going to make an official update today so no need if you rather wait
