### ISSUE TITLE
Go to symbol in workspace only gives partial list

### ISSUE THREAD

**Issue by johnnywz00** [toerob/vscode-tads3tools#20]
With just a minute or two of checking, it seems to me like the symbol finder is only finding user-defined symbols that are not prefaced with any + or ++ marks...   top-level objects seem to be found. 
I notice that it comes back with some method names from the adv3 files, but not all. I don't know that it is listing any user-defined method names; just top-level objects, classes, and functions.

**Comment by toerob** [comment]
I agree, only top-level objects are found. A fix is coming up soon for this.
