### ISSUE TITLE
room property "in" isn't recognized by the outliner

### ISSUE THREAD

**Issue by leugengroot** [toerob/vscode-tads3tools#28]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7923939/145727427-06d9b15a-1cbe-4a1d-8ed3-114812a98573.png)

the direction property for "in" isn not recognized in the outline tree. "out" on the other hand works fine

**To Reproduce**
1. create a project with two rooms
2. link them together with in and out
3. observe the outline in VS Code

**Expected behavior**
Instead of "unnamed" it should read "in".

**Comment by toerob** [comment]
Good catch!
