### ISSUE TITLE
Instructions for Windows Setup

### ISSUE THREAD

**Issue by pieartsy** [toerob/vscode-tads3tools#44]
I wrote instructions on how to set this up for Windows 10 and up (only because I haven't tried with an earlier version of Windows) if you want to add it! If you do so, you can edit anything in it too.
[installing vscode-tads3-tools on windows.md](https://github.com/toerob/vscode-tads3tools/files/13628520/installing.vscode-tads3-tools.on.windows.md)

**Comment by toerob** [comment]
Very good! Thank you! I'll update the README.md and provide a link to it there.
